name: "Build"
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '^1.16.0'
      - name: Run benchmark
        run: make bench | tee bench-output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: bench-output.txt
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          alert-comment-cc-users: "@$GITHUB_ACTOR"
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: go-feature-flag
          tool: 'go'
          output-file-path: bench-output.txt
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
#           auto-push: true
      - name: Checkout target repo
        uses: actions/checkout@v2
        env:
          REPO: thomaspoignant/benchmark-results
          REPO_PATH: benchmark-results
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          repository: "${{ env.REPO }}"
          path: ${{ env.REPO_PATH }}
      - name: Copy index to new repo
        env:
          SOURCE: ./dev/env/*
          TARGET: ./benchmark-results/
        run:
          ls && cp -r ${{ env.SOURCE }} ${{ env.TARGET }} && ls ${{ env.TARGET }}
          
          
      - name: Push
        env:
          REPO_PATH: benchmark-results
          GIT_USERNAME: action
          GIT_EMAIL: action@github.com
        run: |
          cd ${{ env.REPO_PATH }}
          git config --local user.name "${{ env.GIT_USERNAME }}"
          git config --local user.email "${{ env.GIT_EMAIL }}"
          git add .
          git commit -m "Github Actions Automatically Built in `date +"%Y-%m-%d %H:%M"`"
          git push
          
