name: "Build"
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '^1.16.0'
      - run: make lint

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '^1.16.0'
      - run: make test

  Coverage:
    needs: Test
    env:
      COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '^1.16.0'
      - run: make coverage
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.cov

  Docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    #    needs: [ Coverage, Lint ]
    #    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mike
      - run: git config --global user.name "${GITHUB_ACTOR}"
      # we are using --dirty to avoid deleting the perf graphs
      - run: mike deploy --push --update-aliases 0.17.1 latest
      - run: mike set-default --push latest

  Benchmark:
    runs-on: ubuntu-latest
    needs: [ Coverage, Lint ]
    #    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '^1.16.0'
      - name: Run benchmark
        run: make bench | tee bench-output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: bench-output.txt
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          alert-comment-cc-users: "@$GITHUB_ACTOR"
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: go-feature-flag
          tool: 'go'
          output-file-path: bench-output.txt
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: true
